/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import abstracto.*;
import analizadores.Lexer;
import analizadores.Parser;
import structs.Graficar;
import structs.Recorrido;
import java.io.BufferedReader;
import java.io.StringReader;
import java.util.LinkedList;
import symbols.Environment;
import symbols.Vec;
import expressions.*;
import instructions.StructAssig;
import instructions.VarAssig;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author junio
 */
public class MainWindow extends javax.swing.JFrame {
    private Environment global; //= new Environment(null);
    private LinkedList<TError> LError; //= new LinkedList<TError>();
    private LinkedList<ASTNode> lInst;
    private String fileName = "";
    public static String output = "";
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        txt_console.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Run = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_input = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_console = new javax.swing.JTextArea();
        btn_open = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_saveAs = new javax.swing.JButton();
        btn_clean = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_Run.setText("Run");
        btn_Run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RunActionPerformed(evt);
            }
        });

        txt_input.setColumns(20);
        txt_input.setRows(5);
        jScrollPane1.setViewportView(txt_input);

        txt_console.setBackground(new java.awt.Color(0, 0, 0));
        txt_console.setColumns(20);
        txt_console.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txt_console.setForeground(new java.awt.Color(255, 255, 0));
        txt_console.setRows(5);
        jScrollPane2.setViewportView(txt_console);

        btn_open.setText("Open");
        btn_open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_openActionPerformed(evt);
            }
        });

        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_saveAs.setText("Save As");
        btn_saveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveAsActionPerformed(evt);
            }
        });

        btn_clean.setText("Clean");
        btn_clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cleanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_open)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_save)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_saveAs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_clean)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Run)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_open, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_saveAs, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_clean, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(btn_Run, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RunActionPerformed
        String input = txt_input.getText();
        Lexer scanner = new Lexer(new BufferedReader(new StringReader(input)));
        Parser parser = new Parser(scanner);
        
        try {
            parser.parse();
            
            Graficar.graficar(Graficar.Recorrido(parser.root),"AST_proyecto");
            
            global = new Environment(null);
            LError = new LinkedList<>();
            lInst = new LinkedList<>();
            
            Recorrido re = new Recorrido(global, LError, lInst);
            re.Resultado(parser.root);
            //txt_console.setText(((Vec)global.get("var1").getValue()).getValues()[3].toString()+"\n");
            //txt_console.setText(LError.getLast().getLexema()+" "+LError.getFirst().getDescripcion()+"\n");
            txt_console.setText(output);
            output = "";
            
            for(int i=0; i<LError.size(); i++){
                System.out.println(LError.get(i).getLexema() + " : " + LError.get(i).getDescripcion());
            }
        }catch(Exception e){
            
        }
        
        /*global = new Environment(null);
        LError = new LinkedList<>();
        Addition a = new Addition(new Constant(5), new Constant(Float.parseFloat("4.6")));
        VarAssig var1 = new VarAssig("var1", a);
        var1.execute(global, LError);
        LinkedList<ASTNode> l = new LinkedList<>();
        l.add(new Constant(4));
        StructAssig asig = new StructAssig("var1", new Constant(true), l);
        asig.execute(global, LError);
        l.add(new Constant(2));
        StructAssig asig2 = new StructAssig("var1", new Constant(5), l);
        asig2.execute(global, LError);
        
        a = new Addition(new VarRef("var1"), new Constant(new Float("5.5")));
        var1 = new VarAssig("var1", a);
        var1.execute(global, LError);
        int tam = ((Vec)global.get("var1").getValue()).getValues().length;
        Object v[] = ((Vec)global.get("var1").getValue()).getValues();
        
        System.out.println("Tamaño:" + tam + " Tipo: " + global.get("var1").getType().getTypes());
        for(int i = 0; i < tam; i++){
            //txt_console.setText(v[i].toString() + " ");
            System.out.println(v[i].toString());
        }
        
        for(int i=0; i<LError.size(); i++){
            System.out.println(LError.get(i).getLexema() + " : " + LError.get(i).getDescripcion());
        }*/
    }//GEN-LAST:event_btn_RunActionPerformed

    private void btn_openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_openActionPerformed
        JFileChooser fc = new JFileChooser("D:\\Documents\\Universidad\\Compiladores 2\\Proyecto1\\Entradas");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos del lenguaje Arit... *.arit", "arit");
        
        fc.setFileFilter(filter);
        int seleccion = fc.showOpenDialog(txt_input);
        
        if (seleccion == JFileChooser.APPROVE_OPTION)
        {
            File f = fc.getSelectedFile();
            String data = "";
           
            try {
                Scanner sc = new Scanner(f);
                
                while (sc.hasNextLine()) {
                    data += sc.nextLine();
                    data += "\n";
                }
                
                fileName = fc.getSelectedFile().getAbsolutePath();
                txt_input.setText(data);
            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_openActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        if(fileName.equals("")){
            saveFile();
        }else{
            File f = new File(fileName);
        
            try{
                FileWriter fw = new FileWriter(f);
                String text = txt_input.getText();
                fw.write(text);
                fw.close();
            }catch(IOException ex){
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_saveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveAsActionPerformed
        saveFile();
    }//GEN-LAST:event_btn_saveAsActionPerformed

    private void btn_cleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cleanActionPerformed
        txt_input.setText("");
        fileName = "";
    }//GEN-LAST:event_btn_cleanActionPerformed

    private void saveFile(){
        JFileChooser fc = new JFileChooser("D:\\Documents\\Universidad\\Compiladores 2\\Proyecto1\\Entradas");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos del lenguaje Arit... *.arit", "arit");
        
        fc.setFileFilter(filter);
        fc.showSaveDialog(this);
        File f = fc.getSelectedFile();
        
        try{
            FileWriter fw = new FileWriter(f);
            String text = txt_input.getText();
            fw.write(text);
            fw.close();
            
            fileName = fc.getSelectedFile().getAbsolutePath();
        }catch(IOException ex){
            ex.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Run;
    private javax.swing.JButton btn_clean;
    private javax.swing.JButton btn_open;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_saveAs;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea txt_console;
    private javax.swing.JTextArea txt_input;
    // End of variables declaration//GEN-END:variables
}
